# Generated by Django 4.1.4 on 2023-04-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=300)),
            ],
        ),
    ]
